services:
  - postgresql
matrix:
  include:
    - language: node_js
      node_js: '12'
      python: '3.7'
      dist: bionic
      addons: 
        sonarcloud:
          organization: "swsnu"
          token: 
            secure: "iiPTY0p/tKWbN0ind89x/ulj5bEKhZQbMBzL1XNZqgY2IvZ/oDnFrZGkxmInyIZU6hN6KuvgBv120hqWGMkrBn3m6ikcT86grF+bUGZzSj/2s6rfxgrFU2qmh9KxNh5kqGwhxoyuZtHxluD7b5erTwENJJHWH2RCWpldRiEaOichJtpkHPBtdSF83XT7W9NLgFFqXwUViO5BfSCFGVOMyntJMCYAPljCajtaEgJNIsuzeFmDc1LJIj/wjdFHmSAr6ZP76xqCNfRbCPTO7e4HeOR8/Xc/XqSaShjmY4N+Po4o/GryRWrPB88KXQVfR6WienXPFscYSDjk2dHNvNW92K09CqQd8WScodRlf+6JBt01RVWERq8jPW9U9IMoozSV/YGCAT42G+DoTPN9+Lf9hKfpFyICBMHi0rz2hN6ldYmI4atRIrGURWlOvngmkujmgi2XQcsZeQ6Xd3vlAcaFDOfnh5ceG8OuQTJiBYyBbtxYU5qKR+7OR/wRpy1iLphzDK08UwvGCmXypXEDPwtDq5Qv/hi2+A2lP5OMcSqau0bS7yM+F2j+6buFJSbYPKfoKsze1/AJZsoOVgn0TU/qB141AApTmVWJ9tgwWHggM9CDbOPMek/pP1XFmnjRbdgfVZUXgD72mwg3GohGbRoDsISBGSgL2yBLwv3aFO/+9+8="
      cache:
        - yarn: true
        - pip: true
      before_install:
        - cd frontend
      install:
        - yarn install
        - yarn add coveralls
        - gem install coveralls-lcov
        - cd ..
        - cd backend
        - source ~/virtualenv/python3.7/bin/activate
        - pip install -r requirements.txt
        - pip install coveralls
        - python -m pip install Pillow
        - pip install django_cleanup
        - pip install jwt
        - pip install verify_email
        - pip install psycopg2
        - pip install django-sslserver
        - pip install boto3
        - pip install locust
      before_script:
        - psql -c "CREATE DATABASE recipick_database;" -U postgres
        - psql -c "CREATE USER root SUPERUSER;" -U postgres
      script:
        - cd ..
        - cd frontend
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json
        - cd ..
        - cd backend
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test recipick
        - coverage xml
        - cd ..
        - sonar-scanner
      after_success:
        - cd backend
        - coveralls --merge=../frontend/coverage/coverage.json
